### ISSUE TITLE
MongoDB.Driver version miss-match

### ISSUE THREAD

**Issue by kevbite** [ndichiaro/dotnet-mongo#27]
Hello,
Just wondering if there's a way to get around the following issue, when we try to run the tool we get the following exception being thrown (I had to attach a debugger to capture the exception due to this issue - https://github.com/ndichiaro/dotnet-mongo/issues/25).

```
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'MongoDB.Driver, Version=2.14.1.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MongoDB.Bson, Version=2.14.1.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Tools.Net.Mongo.Migrate.Extensions.MigrationExtensions.GetMigrationTypes(FileInfo fileInfo) in D:\a\1\s\src\Tools.Net.Mongo.Migrate\Extensions\MigrationExtensions.cs:line 51
   at Tools.Net.Mongo.Migrate.Operations.UpMigrationOperation.Execute() in D:\a\1\s\src\Tools.Net.Mongo.Migrate\Operations\UpMigrationOperation.cs:line 65
   at Tools.Net.Mongo.Migrate.MigrationRunner.Run(MigrationOptions options) in D:\a\1\s\src\Tools.Net.Mongo.Migrate\MigrationRunner.cs:line 70
   at Tools.Net.Mongo.Handlers.MigrateToolHandler.Run(Queue`1 args) in D:\a\1\s\src\Tools.Net.Mongo\Handlers\MigrateToolHandler.cs:line 45
   at Tools.Net.Mongo.Program.Main(String[] args) in D:\a\1\s\src\Tools.Net.Mongo\Program.cs:line 46
System.IO.FileNotFoundException: Could not load file or assembly 'MongoDB.Driver, Version=2.14.1.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'MongoDB.Driver, Version=2.14.1.0, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'MongoDB.Bson, Version=2.14.1.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'MongoDB.Bson, Version=2.14.1.0, Culture=neutral, PublicKeyToken=null'
```
It seems that because this library is referencing MongoDB.Driver package at version 2.9.1, it can't load the assemblies where our migration classes exist due to it references MongoDB.Driver package at version 2.14.1.

Just wondered if you stumbled on this issue before and if there's a way to mitigate it?

**Comment by ndichiaro** [comment]
Hi @kevbite - Thank you for finding this issue! I haven't run into this specifically so unfortunately I don't have a work around for you off the top of my head but I will start looking into this. 

I'm curious what version of Mongo ` Tools.Net.Mongo.Core` is pulling in if any, since the dependency in Nuget is [MongoDB.Driver (>= 2.9.1)](https://www.nuget.org/packages/Tools.Net.Mongo.Core/) . The tool itself pulls it's Mongo reference from the core package but I suspect in the project where your migrations live if you're importing MongoDB.Driver explicitly it'll use that version instead.  
 
I will start looking into a solution where we keep the MongoDB.Driver version up-to-date in the core package while allowing for a version range to not break any older versions.

**Comment by kevbite** [comment]
Hey @ndichiaro, we're referencing v2.0.0 `Tools.Net.Mongo.Core`. I think it's because our project references MongoDB.Driver itself, so we pull in the latest version. I've tried doing a `2.*` expression for the version but that still wants the latest version too.
I think this might be one of the reasons why EF Core Migrations require a `--startup-project` so that it takes the dependencies from that project instead of the tool loading them in itself? (Might be totally wrong it's just a guess).
Also, is there any need to have the extra `Tools.Net.Mongo.Core` dependency? from checking out the code, it looks like it's not using the `IMigration` marker interface when searching for the migration types?

If you need any help with anything, happy to try to help out where I can.

**Comment by ndichiaro** [comment]
Hey @kevbite - Sorry for the delay in my response. I've been looking into this and if everything stays as is, i.e. `IMigration` and the `Tools.Net.Mongo.Core` reference is still used in the migration file, the problem is how I am loading the assembly [here](https://github.com/ndichiaro/dotnet-mongo/blob/main/src/Tools.Net.Mongo.Migrate/Extensions/MigrationExtensions.cs#L32-L55). It's not pulling any dependencies the migration class may need and causing your error. I have some changes locally that I've been testing that will pull in the required references but we run into a new issue caused by two different version of `MongoDB.Driver` being loaded into the AppDomain. This is resolved if `Tools.Net.Mongo.Core` is updated to contain the latest version of `MongoDB.Driver` and the migration project either doesn't reference it explicitly or it references the same version. 

As for your question "Also, is there any need to have the extra Tools.Net.Mongo.Core dependency?" - from the perspective of running a migration, there isn't a reason for this.  As you pointed out the code pulls from the 'Migrations' folder and doesn't use the interface. I can modify the template that generates the migration files to remove this. However, we'd still see an issue if other dependencies were pulled into the migration, e.g. models from a different assembly. Also, `Tools.Net.Mongo.Core` has some helper/wrapper class around the driver that the original intention was to it easier to get up and running with the mongo driver. If someone wanted to use these classes in their migrations, which I have in a project, the mismatch in versions would still cause an issue. 

As you probably figured out, if you remove `IMigration` and the using statement pulling in `Tools.Net.Mongo.Core` you can run your migrations successfully. Some changes I'm looking to make to help mitigate issues in the future will be:

1. Removing `IMigration` from the template, as this isn't needed for actually performing a migration 
2. Keeping `Tools.Net.Mongo.Core` updated with `MongoDB.Driver` releases but will also update the documentation to recommend keeping any explicit reference to `MongoDB.Driver` the same as `Tools.Net.Mongo.Core` is choosing to use core library classes. 
3. Increased error handling around `MongoDB.Driver` version mismatch to help troubleshoot if this issue does arise. 
4. Updating logic in [here](https://github.com/ndichiaro/dotnet-mongo/blob/main/src/Tools.Net.Mongo.Migrate/Extensions/MigrationExtensions.cs#L32-L55) to pull in referenced assemblies into the AppDomain.

**Comment by kevbite** [comment]
Hey @ndichiaro,

No problem, the changes sound good, I guess one thing to note is when you have a separate assembly where the migrations are you don't get the `MongoDB.Driver` assembly in the bin directory.

But happy to test the changes once you've done the update.

**Comment by ndichiaro** [comment]
@kevbite - Sorry for the significant delay - I opened a PR addressing points 1 and 2 in my previous comment, which will resolve the type mismatch error. I will work on points 3 and 4 in a subsequent PR.  I have a [branch](https://github.com/ndichiaro/dotnet-mongo/commits/fix-version-mismatch) with changes addressing point 4 but they need additional testing.

**Comment by kevbite** [comment]
That's great, thanks for the update 👍
